<div data-bind="scope: 'login'">
    <form>
        <label for="email">Email</label>
        <input type="email" id="email" data-bind="value: email">
        <label for="password">Password</label>
        <input type="password" id="password" data-bind="value: password">
        <button type="button" data-bind="click: submitForm">Login</button>
    </form>
</div>
<script type="text/javascript">
    require(['knockout'], function(ko){
        var viewModel = {
            email: ko.observable(''),
            password: ko.observable(''),
            submitForm: function(){
                alert('Email: ' + this.email() + ', Password: ' + this.password());
            }
        };

        ko.applyBindings(viewModel, document.getElementById('loginForm'));
    });
</script>
